/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  org.jetbrains.annotations.NotNull
 */
package org.bukkit;

import java.util.Set;
import org.bukkit.Bukkit;
import org.bukkit.Fluid;
import org.bukkit.Keyed;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.EntityType;
import org.jetbrains.annotations.NotNull;

public interface Tag<T extends Keyed>
extends Keyed {
    public static final String REGISTRY_BLOCKS = "blocks";
    public static final Tag<Material> WOOL = Bukkit.getTag("blocks", NamespacedKey.minecraft("wool"), Material.class);
    public static final Tag<Material> PLANKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("planks"), Material.class);
    public static final Tag<Material> STONE_BRICKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("stone_bricks"), Material.class);
    public static final Tag<Material> WOODEN_BUTTONS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_buttons"), Material.class);
    public static final Tag<Material> STONE_BUTTONS = Bukkit.getTag("blocks", NamespacedKey.minecraft("stone_buttons"), Material.class);
    public static final Tag<Material> BUTTONS = Bukkit.getTag("blocks", NamespacedKey.minecraft("buttons"), Material.class);
    public static final Tag<Material> WOOL_CARPETS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wool_carpets"), Material.class);
    @Deprecated
    public static final Tag<Material> CARPETS = WOOL_CARPETS;
    public static final Tag<Material> WOODEN_DOORS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_doors"), Material.class);
    public static final Tag<Material> WOODEN_STAIRS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_stairs"), Material.class);
    public static final Tag<Material> WOODEN_SLABS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_slabs"), Material.class);
    public static final Tag<Material> WOODEN_FENCES = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_fences"), Material.class);
    public static final Tag<Material> PRESSURE_PLATES = Bukkit.getTag("blocks", NamespacedKey.minecraft("pressure_plates"), Material.class);
    public static final Tag<Material> WOODEN_PRESSURE_PLATES = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_pressure_plates"), Material.class);
    public static final Tag<Material> STONE_PRESSURE_PLATES = Bukkit.getTag("blocks", NamespacedKey.minecraft("stone_pressure_plates"), Material.class);
    public static final Tag<Material> WOODEN_TRAPDOORS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wooden_trapdoors"), Material.class);
    public static final Tag<Material> DOORS = Bukkit.getTag("blocks", NamespacedKey.minecraft("doors"), Material.class);
    public static final Tag<Material> SAPLINGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("saplings"), Material.class);
    public static final Tag<Material> LOGS_THAT_BURN = Bukkit.getTag("blocks", NamespacedKey.minecraft("logs_that_burn"), Material.class);
    public static final Tag<Material> LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("logs"), Material.class);
    public static final Tag<Material> DARK_OAK_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("dark_oak_logs"), Material.class);
    public static final Tag<Material> OAK_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("oak_logs"), Material.class);
    public static final Tag<Material> BIRCH_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("birch_logs"), Material.class);
    public static final Tag<Material> ACACIA_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("acacia_logs"), Material.class);
    public static final Tag<Material> CHERRY_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("cherry_logs"), Material.class);
    public static final Tag<Material> JUNGLE_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("jungle_logs"), Material.class);
    public static final Tag<Material> SPRUCE_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("spruce_logs"), Material.class);
    public static final Tag<Material> MANGROVE_LOGS = Bukkit.getTag("blocks", NamespacedKey.minecraft("mangrove_logs"), Material.class);
    public static final Tag<Material> CRIMSON_STEMS = Bukkit.getTag("blocks", NamespacedKey.minecraft("crimson_stems"), Material.class);
    public static final Tag<Material> WARPED_STEMS = Bukkit.getTag("blocks", NamespacedKey.minecraft("warped_stems"), Material.class);
    public static final Tag<Material> BAMBOO_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("bamboo_blocks"), Material.class);
    public static final Tag<Material> BANNERS = Bukkit.getTag("blocks", NamespacedKey.minecraft("banners"), Material.class);
    public static final Tag<Material> SAND = Bukkit.getTag("blocks", NamespacedKey.minecraft("sand"), Material.class);
    public static final Tag<Material> SMELTS_TO_GLASS = Bukkit.getTag("blocks", NamespacedKey.minecraft("smelts_to_glass"), Material.class);
    public static final Tag<Material> STAIRS = Bukkit.getTag("blocks", NamespacedKey.minecraft("stairs"), Material.class);
    public static final Tag<Material> SLABS = Bukkit.getTag("blocks", NamespacedKey.minecraft("slabs"), Material.class);
    public static final Tag<Material> WALLS = Bukkit.getTag("blocks", NamespacedKey.minecraft("walls"), Material.class);
    public static final Tag<Material> ANVIL = Bukkit.getTag("blocks", NamespacedKey.minecraft("anvil"), Material.class);
    public static final Tag<Material> RAILS = Bukkit.getTag("blocks", NamespacedKey.minecraft("rails"), Material.class);
    public static final Tag<Material> LEAVES = Bukkit.getTag("blocks", NamespacedKey.minecraft("leaves"), Material.class);
    public static final Tag<Material> TRAPDOORS = Bukkit.getTag("blocks", NamespacedKey.minecraft("trapdoors"), Material.class);
    public static final Tag<Material> FLOWER_POTS = Bukkit.getTag("blocks", NamespacedKey.minecraft("flower_pots"), Material.class);
    public static final Tag<Material> SMALL_FLOWERS = Bukkit.getTag("blocks", NamespacedKey.minecraft("small_flowers"), Material.class);
    public static final Tag<Material> BEDS = Bukkit.getTag("blocks", NamespacedKey.minecraft("beds"), Material.class);
    public static final Tag<Material> FENCES = Bukkit.getTag("blocks", NamespacedKey.minecraft("fences"), Material.class);
    public static final Tag<Material> TALL_FLOWERS = Bukkit.getTag("blocks", NamespacedKey.minecraft("tall_flowers"), Material.class);
    public static final Tag<Material> FLOWERS = Bukkit.getTag("blocks", NamespacedKey.minecraft("flowers"), Material.class);
    public static final Tag<Material> PIGLIN_REPELLENTS = Bukkit.getTag("blocks", NamespacedKey.minecraft("piglin_repellents"), Material.class);
    public static final Tag<Material> GOLD_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("gold_ores"), Material.class);
    public static final Tag<Material> IRON_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("iron_ores"), Material.class);
    public static final Tag<Material> DIAMOND_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("diamond_ores"), Material.class);
    public static final Tag<Material> REDSTONE_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("redstone_ores"), Material.class);
    public static final Tag<Material> LAPIS_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("lapis_ores"), Material.class);
    public static final Tag<Material> COAL_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("coal_ores"), Material.class);
    public static final Tag<Material> EMERALD_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("emerald_ores"), Material.class);
    public static final Tag<Material> COPPER_ORES = Bukkit.getTag("blocks", NamespacedKey.minecraft("copper_ores"), Material.class);
    public static final Tag<Material> CANDLES = Bukkit.getTag("blocks", NamespacedKey.minecraft("candles"), Material.class);
    public static final Tag<Material> DIRT = Bukkit.getTag("blocks", NamespacedKey.minecraft("dirt"), Material.class);
    public static final Tag<Material> TERRACOTTA = Bukkit.getTag("blocks", NamespacedKey.minecraft("terracotta"), Material.class);
    public static final Tag<Material> COMPLETES_FIND_TREE_TUTORIAL = Bukkit.getTag("blocks", NamespacedKey.minecraft("completes_find_tree_tutorial"), Material.class);
    public static final Tag<Material> ENDERMAN_HOLDABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("enderman_holdable"), Material.class);
    public static final Tag<Material> ICE = Bukkit.getTag("blocks", NamespacedKey.minecraft("ice"), Material.class);
    public static final Tag<Material> VALID_SPAWN = Bukkit.getTag("blocks", NamespacedKey.minecraft("valid_spawn"), Material.class);
    public static final Tag<Material> IMPERMEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("impermeable"), Material.class);
    public static final Tag<Material> UNDERWATER_BONEMEALS = Bukkit.getTag("blocks", NamespacedKey.minecraft("underwater_bonemeals"), Material.class);
    public static final Tag<Material> CORAL_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("coral_blocks"), Material.class);
    public static final Tag<Material> WALL_CORALS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wall_corals"), Material.class);
    public static final Tag<Material> CORAL_PLANTS = Bukkit.getTag("blocks", NamespacedKey.minecraft("coral_plants"), Material.class);
    public static final Tag<Material> CORALS = Bukkit.getTag("blocks", NamespacedKey.minecraft("corals"), Material.class);
    public static final Tag<Material> BAMBOO_PLANTABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("bamboo_plantable_on"), Material.class);
    public static final Tag<Material> STANDING_SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("standing_signs"), Material.class);
    public static final Tag<Material> WALL_SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wall_signs"), Material.class);
    public static final Tag<Material> SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("signs"), Material.class);
    public static final Tag<Material> CEILING_HANGING_SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("ceiling_hanging_signs"), Material.class);
    public static final Tag<Material> WALL_HANGING_SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wall_hanging_signs"), Material.class);
    public static final Tag<Material> ALL_HANGING_SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("all_hanging_signs"), Material.class);
    public static final Tag<Material> ALL_SIGNS = Bukkit.getTag("blocks", NamespacedKey.minecraft("all_signs"), Material.class);
    public static final Tag<Material> DRAGON_IMMUNE = Bukkit.getTag("blocks", NamespacedKey.minecraft("dragon_immune"), Material.class);
    public static final Tag<Material> DRAGON_TRANSPARENT = Bukkit.getTag("blocks", NamespacedKey.minecraft("dragon_transparent"), Material.class);
    public static final Tag<Material> WITHER_IMMUNE = Bukkit.getTag("blocks", NamespacedKey.minecraft("wither_immune"), Material.class);
    public static final Tag<Material> WITHER_SUMMON_BASE_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wither_summon_base_blocks"), Material.class);
    public static final Tag<Material> BEEHIVES = Bukkit.getTag("blocks", NamespacedKey.minecraft("beehives"), Material.class);
    public static final Tag<Material> CROPS = Bukkit.getTag("blocks", NamespacedKey.minecraft("crops"), Material.class);
    public static final Tag<Material> BEE_GROWABLES = Bukkit.getTag("blocks", NamespacedKey.minecraft("bee_growables"), Material.class);
    public static final Tag<Material> PORTALS = Bukkit.getTag("blocks", NamespacedKey.minecraft("portals"), Material.class);
    public static final Tag<Material> FIRE = Bukkit.getTag("blocks", NamespacedKey.minecraft("fire"), Material.class);
    public static final Tag<Material> NYLIUM = Bukkit.getTag("blocks", NamespacedKey.minecraft("nylium"), Material.class);
    public static final Tag<Material> WART_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("wart_blocks"), Material.class);
    public static final Tag<Material> BEACON_BASE_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("beacon_base_blocks"), Material.class);
    public static final Tag<Material> SOUL_SPEED_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("soul_speed_blocks"), Material.class);
    public static final Tag<Material> WALL_POST_OVERRIDE = Bukkit.getTag("blocks", NamespacedKey.minecraft("wall_post_override"), Material.class);
    public static final Tag<Material> CLIMBABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("climbable"), Material.class);
    public static final Tag<Material> FALL_DAMAGE_RESETTING = Bukkit.getTag("blocks", NamespacedKey.minecraft("fall_damage_resetting"), Material.class);
    public static final Tag<Material> SHULKER_BOXES = Bukkit.getTag("blocks", NamespacedKey.minecraft("shulker_boxes"), Material.class);
    public static final Tag<Material> HOGLIN_REPELLENTS = Bukkit.getTag("blocks", NamespacedKey.minecraft("hoglin_repellents"), Material.class);
    public static final Tag<Material> SOUL_FIRE_BASE_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("soul_fire_base_blocks"), Material.class);
    public static final Tag<Material> STRIDER_WARM_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("strider_warm_blocks"), Material.class);
    public static final Tag<Material> CAMPFIRES = Bukkit.getTag("blocks", NamespacedKey.minecraft("campfires"), Material.class);
    public static final Tag<Material> GUARDED_BY_PIGLINS = Bukkit.getTag("blocks", NamespacedKey.minecraft("guarded_by_piglins"), Material.class);
    public static final Tag<Material> PREVENT_MOB_SPAWNING_INSIDE = Bukkit.getTag("blocks", NamespacedKey.minecraft("prevent_mob_spawning_inside"), Material.class);
    public static final Tag<Material> FENCE_GATES = Bukkit.getTag("blocks", NamespacedKey.minecraft("fence_gates"), Material.class);
    public static final Tag<Material> UNSTABLE_BOTTOM_CENTER = Bukkit.getTag("blocks", NamespacedKey.minecraft("unstable_bottom_center"), Material.class);
    public static final Tag<Material> MUSHROOM_GROW_BLOCK = Bukkit.getTag("blocks", NamespacedKey.minecraft("mushroom_grow_block"), Material.class);
    public static final Tag<Material> INFINIBURN_OVERWORLD = Bukkit.getTag("blocks", NamespacedKey.minecraft("infiniburn_overworld"), Material.class);
    public static final Tag<Material> INFINIBURN_NETHER = Bukkit.getTag("blocks", NamespacedKey.minecraft("infiniburn_nether"), Material.class);
    public static final Tag<Material> INFINIBURN_END = Bukkit.getTag("blocks", NamespacedKey.minecraft("infiniburn_end"), Material.class);
    public static final Tag<Material> BASE_STONE_OVERWORLD = Bukkit.getTag("blocks", NamespacedKey.minecraft("base_stone_overworld"), Material.class);
    public static final Tag<Material> STONE_ORE_REPLACEABLES = Bukkit.getTag("blocks", NamespacedKey.minecraft("stone_ore_replaceables"), Material.class);
    public static final Tag<Material> DEEPSLATE_ORE_REPLACEABLES = Bukkit.getTag("blocks", NamespacedKey.minecraft("deepslate_ore_replaceables"), Material.class);
    public static final Tag<Material> BASE_STONE_NETHER = Bukkit.getTag("blocks", NamespacedKey.minecraft("base_stone_nether"), Material.class);
    public static final Tag<Material> OVERWORLD_CARVER_REPLACEABLES = Bukkit.getTag("blocks", NamespacedKey.minecraft("overworld_carver_replaceables"), Material.class);
    public static final Tag<Material> NETHER_CARVER_REPLACEABLES = Bukkit.getTag("blocks", NamespacedKey.minecraft("nether_carver_replaceables"), Material.class);
    public static final Tag<Material> CANDLE_CAKES = Bukkit.getTag("blocks", NamespacedKey.minecraft("candle_cakes"), Material.class);
    public static final Tag<Material> CAULDRONS = Bukkit.getTag("blocks", NamespacedKey.minecraft("cauldrons"), Material.class);
    public static final Tag<Material> CRYSTAL_SOUND_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("crystal_sound_blocks"), Material.class);
    public static final Tag<Material> INSIDE_STEP_SOUND_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("inside_step_sound_blocks"), Material.class);
    public static final Tag<Material> COMBINATION_STEP_SOUND_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("combination_step_sound_blocks"), Material.class);
    public static final Tag<Material> OCCLUDES_VIBRATION_SIGNALS = Bukkit.getTag("blocks", NamespacedKey.minecraft("occludes_vibration_signals"), Material.class);
    public static final Tag<Material> DAMPENS_VIBRATIONS = Bukkit.getTag("blocks", NamespacedKey.minecraft("dampens_vibrations"), Material.class);
    public static final Tag<Material> DRIPSTONE_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("dripstone_replaceable_blocks"), Material.class);
    public static final Tag<Material> CAVE_VINES = Bukkit.getTag("blocks", NamespacedKey.minecraft("cave_vines"), Material.class);
    public static final Tag<Material> MOSS_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("moss_replaceable"), Material.class);
    public static final Tag<Material> LUSH_GROUND_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("lush_ground_replaceable"), Material.class);
    public static final Tag<Material> AZALEA_ROOT_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("azalea_root_replaceable"), Material.class);
    public static final Tag<Material> SMALL_DRIPLEAF_PLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("small_dripleaf_placeable"), Material.class);
    public static final Tag<Material> BIG_DRIPLEAF_PLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("big_dripleaf_placeable"), Material.class);
    public static final Tag<Material> SNOW = Bukkit.getTag("blocks", NamespacedKey.minecraft("snow"), Material.class);
    public static final Tag<Material> MINEABLE_AXE = Bukkit.getTag("blocks", NamespacedKey.minecraft("mineable/axe"), Material.class);
    public static final Tag<Material> MINEABLE_HOE = Bukkit.getTag("blocks", NamespacedKey.minecraft("mineable/hoe"), Material.class);
    public static final Tag<Material> MINEABLE_PICKAXE = Bukkit.getTag("blocks", NamespacedKey.minecraft("mineable/pickaxe"), Material.class);
    public static final Tag<Material> MINEABLE_SHOVEL = Bukkit.getTag("blocks", NamespacedKey.minecraft("mineable/shovel"), Material.class);
    public static final Tag<Material> SWORD_EFFICIENT = Bukkit.getTag("blocks", NamespacedKey.minecraft("sword_efficient"), Material.class);
    public static final Tag<Material> NEEDS_DIAMOND_TOOL = Bukkit.getTag("blocks", NamespacedKey.minecraft("needs_diamond_tool"), Material.class);
    public static final Tag<Material> NEEDS_IRON_TOOL = Bukkit.getTag("blocks", NamespacedKey.minecraft("needs_iron_tool"), Material.class);
    public static final Tag<Material> NEEDS_STONE_TOOL = Bukkit.getTag("blocks", NamespacedKey.minecraft("needs_stone_tool"), Material.class);
    public static final Tag<Material> FEATURES_CANNOT_REPLACE = Bukkit.getTag("blocks", NamespacedKey.minecraft("features_cannot_replace"), Material.class);
    public static final Tag<Material> LAVA_POOL_STONE_CANNOT_REPLACE = Bukkit.getTag("blocks", NamespacedKey.minecraft("lava_pool_stone_cannot_replace"), Material.class);
    public static final Tag<Material> GEODE_INVALID_BLOCKS = Bukkit.getTag("blocks", NamespacedKey.minecraft("geode_invalid_blocks"), Material.class);
    public static final Tag<Material> FROG_PREFER_JUMP_TO = Bukkit.getTag("blocks", NamespacedKey.minecraft("frog_prefer_jump_to"), Material.class);
    public static final Tag<Material> SCULK_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("sculk_replaceable"), Material.class);
    public static final Tag<Material> SCULK_REPLACEABLE_WORLD_GEN = Bukkit.getTag("blocks", NamespacedKey.minecraft("sculk_replaceable_world_gen"), Material.class);
    public static final Tag<Material> ANCIENT_CITY_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("ancient_city_replaceable"), Material.class);
    public static final Tag<Material> VIBRATION_RESONATORS = Bukkit.getTag("blocks", NamespacedKey.minecraft("vibration_resonators"), Material.class);
    public static final Tag<Material> ANIMALS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("animals_spawnable_on"), Material.class);
    public static final Tag<Material> AXOLOTLS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("axolotls_spawnable_on"), Material.class);
    public static final Tag<Material> GOATS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("goats_spawnable_on"), Material.class);
    public static final Tag<Material> MOOSHROOMS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("mooshrooms_spawnable_on"), Material.class);
    public static final Tag<Material> PARROTS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("parrots_spawnable_on"), Material.class);
    public static final Tag<Material> POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = Bukkit.getTag("blocks", NamespacedKey.minecraft("polar_bears_spawnable_on_alternate"), Material.class);
    public static final Tag<Material> RABBITS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("rabbits_spawnable_on"), Material.class);
    public static final Tag<Material> FOXES_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("foxes_spawnable_on"), Material.class);
    public static final Tag<Material> WOLVES_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("wolves_spawnable_on"), Material.class);
    public static final Tag<Material> FROGS_SPAWNABLE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("frogs_spawnable_on"), Material.class);
    public static final Tag<Material> AZALEA_GROWS_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("azalea_grows_on"), Material.class);
    public static final Tag<Material> CONVERTABLE_TO_MUD = Bukkit.getTag("blocks", NamespacedKey.minecraft("convertable_to_mud"), Material.class);
    public static final Tag<Material> MANGROVE_LOGS_CAN_GROW_THROUGH = Bukkit.getTag("blocks", NamespacedKey.minecraft("mangrove_logs_can_grow_through"), Material.class);
    public static final Tag<Material> MANGROVE_ROOTS_CAN_GROW_THROUGH = Bukkit.getTag("blocks", NamespacedKey.minecraft("mangrove_roots_can_grow_through"), Material.class);
    public static final Tag<Material> DEAD_BUSH_MAY_PLACE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("dead_bush_may_place_on"), Material.class);
    public static final Tag<Material> SNAPS_GOAT_HORN = Bukkit.getTag("blocks", NamespacedKey.minecraft("snaps_goat_horn"), Material.class);
    public static final Tag<Material> REPLACEABLE_BY_TREES = Bukkit.getTag("blocks", NamespacedKey.minecraft("replaceable_by_trees"), Material.class);
    public static final Tag<Material> SNOW_LAYER_CANNOT_SURVIVE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("snow_layer_cannot_survive_on"), Material.class);
    public static final Tag<Material> SNOW_LAYER_CAN_SURVIVE_ON = Bukkit.getTag("blocks", NamespacedKey.minecraft("snow_layer_can_survive_on"), Material.class);
    public static final Tag<Material> INVALID_SPAWN_INSIDE = Bukkit.getTag("blocks", NamespacedKey.minecraft("invalid_spawn_inside"), Material.class);
    public static final Tag<Material> SNIFFER_DIGGABLE_BLOCK = Bukkit.getTag("blocks", NamespacedKey.minecraft("sniffer_diggable_block"), Material.class);
    public static final Tag<Material> SNIFFER_EGG_HATCH_BOOST = Bukkit.getTag("blocks", NamespacedKey.minecraft("sniffer_egg_hatch_boost"), Material.class);
    public static final Tag<Material> TRAIL_RUINS_REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("trail_ruins_replaceable"), Material.class);
    public static final Tag<Material> REPLACEABLE = Bukkit.getTag("blocks", NamespacedKey.minecraft("replaceable"), Material.class);
    public static final Tag<Material> ENCHANTMENT_POWER_PROVIDER = Bukkit.getTag("blocks", NamespacedKey.minecraft("enchantment_power_provider"), Material.class);
    public static final Tag<Material> ENCHANTMENT_POWER_TRANSMITTER = Bukkit.getTag("blocks", NamespacedKey.minecraft("enchantment_power_transmitter"), Material.class);
    public static final Tag<Material> MAINTAINS_FARMLAND = Bukkit.getTag("blocks", NamespacedKey.minecraft("maintains_farmland"), Material.class);
    public static final String REGISTRY_ITEMS = "items";
    public static final Tag<Material> ITEMS_PIGLIN_LOVED = Bukkit.getTag("items", NamespacedKey.minecraft("piglin_loved"), Material.class);
    public static final Tag<Material> IGNORED_BY_PIGLIN_BABIES = Bukkit.getTag("items", NamespacedKey.minecraft("ignored_by_piglin_babies"), Material.class);
    public static final Tag<Material> PIGLIN_FOOD = Bukkit.getTag("items", NamespacedKey.minecraft("piglin_food"), Material.class);
    public static final Tag<Material> FOX_FOOD = Bukkit.getTag("items", NamespacedKey.minecraft("fox_food"), Material.class);
    public static final Tag<Material> ITEMS_BANNERS = Bukkit.getTag("items", NamespacedKey.minecraft("banners"), Material.class);
    public static final Tag<Material> ITEMS_BOATS = Bukkit.getTag("items", NamespacedKey.minecraft("boats"), Material.class);
    public static final Tag<Material> ITEMS_CHEST_BOATS = Bukkit.getTag("items", NamespacedKey.minecraft("chest_boats"), Material.class);
    public static final Tag<Material> ITEMS_FISHES = Bukkit.getTag("items", NamespacedKey.minecraft("fishes"), Material.class);
    public static final Tag<Material> ITEMS_MUSIC_DISCS = Bukkit.getTag("items", NamespacedKey.minecraft("music_discs"), Material.class);
    public static final Tag<Material> ITEMS_CREEPER_DROP_MUSIC_DISCS = Bukkit.getTag("items", NamespacedKey.minecraft("creeper_drop_music_discs"), Material.class);
    public static final Tag<Material> ITEMS_COALS = Bukkit.getTag("items", NamespacedKey.minecraft("coals"), Material.class);
    public static final Tag<Material> ITEMS_ARROWS = Bukkit.getTag("items", NamespacedKey.minecraft("arrows"), Material.class);
    public static final Tag<Material> ITEMS_LECTERN_BOOKS = Bukkit.getTag("items", NamespacedKey.minecraft("lectern_books"), Material.class);
    public static final Tag<Material> ITEMS_BOOKSHELF_BOOKS = Bukkit.getTag("items", NamespacedKey.minecraft("bookshelf_books"), Material.class);
    public static final Tag<Material> ITEMS_BEACON_PAYMENT_ITEMS = Bukkit.getTag("items", NamespacedKey.minecraft("beacon_payment_items"), Material.class);
    public static final Tag<Material> ITEMS_STONE_TOOL_MATERIALS = Bukkit.getTag("items", NamespacedKey.minecraft("stone_tool_materials"), Material.class);
    public static final Tag<Material> ITEMS_FURNACE_MATERIALS = Bukkit.getTag("items", NamespacedKey.minecraft("furnace_materials"), Material.class);
    public static final Tag<Material> ITEMS_COMPASSES = Bukkit.getTag("items", NamespacedKey.minecraft("compasses"), Material.class);
    public static final Tag<Material> ITEMS_HANGING_SIGNS = Bukkit.getTag("items", NamespacedKey.minecraft("hanging_signs"), Material.class);
    public static final Tag<Material> ITEMS_CREEPER_IGNITERS = Bukkit.getTag("items", NamespacedKey.minecraft("creeper_igniters"), Material.class);
    public static final Tag<Material> ITEMS_NOTE_BLOCK_TOP_INSTRUMENTS = Bukkit.getTag("items", NamespacedKey.minecraft("noteblock_top_instruments"), Material.class);
    public static final Tag<Material> ITEMS_TRIMMABLE_ARMOR = Bukkit.getTag("items", NamespacedKey.minecraft("trimmable_armor"), Material.class);
    public static final Tag<Material> ITEMS_TRIM_MATERIALS = Bukkit.getTag("items", NamespacedKey.minecraft("trim_materials"), Material.class);
    public static final Tag<Material> ITEMS_TRIM_TEMPLATES = Bukkit.getTag("items", NamespacedKey.minecraft("trim_templates"), Material.class);
    public static final Tag<Material> ITEMS_SNIFFER_FOOD = Bukkit.getTag("items", NamespacedKey.minecraft("sniffer_food"), Material.class);
    public static final Tag<Material> ITEMS_DECORATED_POT_SHERDS = Bukkit.getTag("items", NamespacedKey.minecraft("decorated_pot_sherds"), Material.class);
    public static final Tag<Material> ITEMS_DECORATED_POT_INGREDIENTS = Bukkit.getTag("items", NamespacedKey.minecraft("decorated_pot_ingredients"), Material.class);
    public static final Tag<Material> ITEMS_SWORDS = Bukkit.getTag("items", NamespacedKey.minecraft("swords"), Material.class);
    public static final Tag<Material> ITEMS_AXES = Bukkit.getTag("items", NamespacedKey.minecraft("axes"), Material.class);
    public static final Tag<Material> ITEMS_HOES = Bukkit.getTag("items", NamespacedKey.minecraft("hoes"), Material.class);
    public static final Tag<Material> ITEMS_PICKAXES = Bukkit.getTag("items", NamespacedKey.minecraft("pickaxes"), Material.class);
    public static final Tag<Material> ITEMS_SHOVELS = Bukkit.getTag("items", NamespacedKey.minecraft("shovels"), Material.class);
    public static final Tag<Material> ITEMS_TOOLS = Bukkit.getTag("items", NamespacedKey.minecraft("tools"), Material.class);
    public static final Tag<Material> ITEMS_BREAKS_DECORATED_POTS = Bukkit.getTag("items", NamespacedKey.minecraft("breaks_decorated_pots"), Material.class);
    public static final Tag<Material> ITEMS_VILLAGER_PLANTABLE_SEEDS = Bukkit.getTag("items", NamespacedKey.minecraft("villager_plantable_seeds"), Material.class);
    public static final Tag<Material> FREEZE_IMMUNE_WEARABLES = Bukkit.getTag("items", NamespacedKey.minecraft("freeze_immune_wearables"), Material.class);
    public static final Tag<Material> AXOLOTL_TEMPT_ITEMS = Bukkit.getTag("items", NamespacedKey.minecraft("axolotl_tempt_items"), Material.class);
    public static final Tag<Material> CLUSTER_MAX_HARVESTABLES = Bukkit.getTag("items", NamespacedKey.minecraft("cluster_max_harvestables"), Material.class);
    public static final String REGISTRY_FLUIDS = "fluids";
    public static final Tag<Fluid> FLUIDS_LAVA = Bukkit.getTag("fluids", NamespacedKey.minecraft("lava"), Fluid.class);
    public static final Tag<Fluid> FLUIDS_WATER = Bukkit.getTag("fluids", NamespacedKey.minecraft("water"), Fluid.class);
    public static final String REGISTRY_ENTITY_TYPES = "entity_types";
    public static final Tag<EntityType> ENTITY_TYPES_SKELETONS = Bukkit.getTag("entity_types", NamespacedKey.minecraft("skeletons"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_RAIDERS = Bukkit.getTag("entity_types", NamespacedKey.minecraft("raiders"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_BEEHIVE_INHABITORS = Bukkit.getTag("entity_types", NamespacedKey.minecraft("beehive_inhabitors"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_ARROWS = Bukkit.getTag("entity_types", NamespacedKey.minecraft("arrows"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_IMPACT_PROJECTILES = Bukkit.getTag("entity_types", NamespacedKey.minecraft("impact_projectiles"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_POWDER_SNOW_WALKABLE_MOBS = Bukkit.getTag("entity_types", NamespacedKey.minecraft("powder_snow_walkable_mobs"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_AXOLOTL_ALWAYS_HOSTILES = Bukkit.getTag("entity_types", NamespacedKey.minecraft("axolotl_always_hostiles"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_AXOLOTL_HUNT_TARGETS = Bukkit.getTag("entity_types", NamespacedKey.minecraft("axolotl_hunt_targets"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_FREEZE_IMMUNE_ENTITY_TYPES = Bukkit.getTag("entity_types", NamespacedKey.minecraft("freeze_immune_entity_types"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_FREEZE_HURTS_EXTRA_TYPES = Bukkit.getTag("entity_types", NamespacedKey.minecraft("freeze_hurts_extra_types"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_FROG_FOOD = Bukkit.getTag("entity_types", NamespacedKey.minecraft("frog_food"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_FALL_DAMAGE_IMMUNE = Bukkit.getTag("entity_types", NamespacedKey.minecraft("fall_damage_immune"), EntityType.class);
    public static final Tag<EntityType> ENTITY_TYPES_DISMOUNTS_UNDERWATER = Bukkit.getTag("entity_types", NamespacedKey.minecraft("dismounts_underwater"), EntityType.class);

    public boolean isTagged(@NotNull T var1);

    @NotNull
    public Set<T> getValues();
}

